[package]
name = "verifier-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
jolt-core = { package = "jolt-core", path = "../../../jolt-core" }
